Portfolio: details popup window
beteland123/Portfolio pull request #14
Opened 2023-04-21 04:29 UTC by beteland123

implement the following interactions:

   When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
  When the user clicks (or taps) the close (X) button, the popup disappears.

- use a JavaScript array to store all of the information for all projects.

-update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. 
- implement the popup window.

2023-04-21 17:18 UTC, OyePriscilla requested changes
Hi @beteland123 and @Xecyc 👏 👏 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Populate project cards dynamically with JS ✔️ 
Use JavaScript to manipulate DOM elements ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 17:18 UTC, OyePriscilla commented on index.html
> +              fill="none"
- [ ] Kindly render the pop-up section dynamically with JS according to the project requirement. 👍

2023-04-21 17:18 UTC, OyePriscilla commented on index.html
> +                        >See live
- [ ] Please kindly design the elements of this container (**for mobile version**) according to the given template.

> |     |Your Design                                 | Figma Design                                  |     |
> | --- | ----------------------------------------------- | ------------------------------------------------ | --- |
> |     |  <img width="225" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/233694103-9e759707-d475-41d5-9e64-fcc9929cf5f4.png">| <img width="128" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/233694281-ab6155d7-4722-4315-a4a5-710ea65dcb77.png">
|

2023-04-21 17:18 UTC, OyePriscilla commented on style.css
> +  }
- [ ] Kindly correct this anomaly, I observed that the modal for the mobile version is not yet fixed on the UI, and this made other part of the app to be scrollable. 👍 

<img width="275" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/233695967-4be6d023-a664-48fc-87d6-85606edcedf7.png">

2023-04-21 21:33 UTC, AdnanOlarmmi requested changes
Hi @beteland123, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice one rendering the pop up dynamically.
- Nice one taking to the requested changes.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 21:33 UTC, AdnanOlarmmi commented on index.html
> +                        >See live
> 

- [ ] Nice one trying to fix the design as requested by the previous reviewer, please, kindly note that this has created another bug, kindly fix this to match the Figma design above.

- Your design

<img width="158" alt="image" src="https://user-images.githubusercontent.com/41163571/233737360-d0e14ec9-cd50-4ecb-993e-2f53bc4c4345.png">

- The left, bottom and top margins of technologies `html css javascript`.

- The overflow of the seelive and the border and icon of the see source buttons respectively.

2023-04-22 05:48 UTC, jerryowusu approved these changes
Hi @beteland123 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![kpop-approved](https://user-images.githubusercontent.com/65233860/233765361-71eb6a2e-a88a-4eff-8794-2c481ac4c077.gif)


## Highlights
:heavy_check_mark: Nice effort in making the requested changes
:heavy_check_mark: Used JavaScript to manipulate DOM elements 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 05:49 UTC, merged